name: 'integration'

on:
  - workflow_dispatch

jobs:
  trigger:
    name: "Call repository_dispach"
    strategy:
      fail-fast: false
      matrix:
        repository: ["app1","app2"]
    runs-on: [self-hosted,Linux,X64]
    steps:
    - uses: actions/checkout@v3
    
    - uses: passeidireto/trigger-external-workflow-action@main
      with:
        repository: kamoteam/${{ matrix.repository }}
        event: "Cluster-Integration"
        github_pat: ${{ secrets.PAT }}

  wait:
    name: "Wait trigger jobs"
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        repository: ["app1","app2"]
    runs-on: [self-hosted,Linux,X64]
    needs: trigger
    steps:
    - uses: actions/checkout@v3

    # - name: Wait for tests to succeed
    #   uses: fountainhead/action-wait-for-check@v1.0.0
    #   with:
    #     ref: main
    #     checkName: 'Tear Down'
    #     token: ${{ secrets.PAT }}
    #     intervalSeconds: 10
    #     owner: kamoteam
    #     repo: ${{ matrix.repository }}

    - name: Trigger Workflow and Wait
      uses: convictional/trigger-workflow-and-wait@v1.6.3

      with:
        owner: kamoteam
        repo: ${{ matrix.repository }}
        github_token: ${{ secrets.PAT }}
        workflow_file_name: ci.yml
        ref: main
