name: 'integration'

on:
  - workflow_dispatch

jobs:
  trigger:
    name: "Call repository_dispach"
    runs-on: [self-hosted,Linux,X64]
    steps:
    - uses: actions/checkout@v3
    
    - uses: passeidireto/trigger-external-workflow-action@main
      with:
        repository: kamoteam/app1
        event: trigger
        github_pat: ${{ secrets.PAT }}

    - uses: passeidireto/trigger-external-workflow-action@main
      with:
        repository: kamoteam/app2
        event: trigger
        github_pat: ${{ secrets.PAT }}

  wait:
    name: "Wait trigger jobs"
    runs-on: [self-hosted,Linux,X64]
    needs: trigger
    steps:
    - uses: actions/checkout@v3

    - name: Wait for tests to succeed
      uses: kelu27/wait-on-check-action@v1
      with:
        ref: ${{ github.ref }}
        check-name: 'Tear Down'
        repo-token: ${{ secrets.PAT }}
        wait-interval: 10
        owner: kamoteam
        repo: app1

    - name: Wait for tests to succeed
      uses: kelu27/wait-on-check-action@v1
      with:
        ref: ${{ github.ref }}
        check-name: 'Tear Down'
        repo-token: ${{ secrets.PAT }}
        wait-interval: 10
        owner: kamoteam
        repo: app2
